### ISSUE TITLE
Does not hande cases when command is empty

### ISSUE THREAD

**Issue by vpal** [assaflavie/runlike#2]
```
# runlike d57e739ff259
Traceback (most recent call last):
  File "/tmp/runlike/bin/runlike", line 9, in <module>
    load_entry_point('runlike==0.1.2', 'console_scripts', 'runlike')()
  File "/tmp/runlike/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/runlike/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/tmp/runlike/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/runlike/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/tmp/runlike/local/lib/python2.7/site-packages/runlike.py", line 126, in cli
    print ins.format_cli()
  File "/tmp/runlike/local/lib/python2.7/site-packages/runlike.py", line 111, in format_cli
    parameters = joiner.join(parameters)
TypeError: sequence item 25: expected string or Unicode, list found
```
After printing the parameters variable before
`parameters = joiner.join(parameters)`
it turns out that the last element of the list is also a list.
It seems like the issues is related to this code:
```
        command = []
        cmd = self.get_fact("Config.Cmd")
        if cmd:
            command = " ".join(cmd)
parameters.append(command)
```
If someone is using for example entrypoint and the command is empty the cmd string will be empty and a list is appended instead of a string, because the if is never evaluated.

**Comment by assaflavie** [comment]
Thanks. Should be fixed now.
